/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_07;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.accessibility.AccessibleContext;
import org.json.JSONObject;

/**
 *
 * @author PC
 */
public class DisplayLessons extends javax.swing.JFrame {

    private LessonManager manager = new LessonManager();
    private JList<String> lessonList;
    private JTextArea lessonContent;
    private JButton completeBtn;

    private ArrayList<Lesson> lessons;
    private String courseId;
    private String userId;

    public DisplayLessons(String courseId, String userId) {
        this.courseId = courseId;
        this.userId = userId;

        setTitle("Lessons");
        setSize(700, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        lessons = manager.getLessonsByCourse(courseId);

        // List
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Lesson l : lessons) {
            model.addElement(l.getLessonId() + " - " + l.getTitle());
        }

        lessonList = new JList<>(model);
        lessonList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        add(new JScrollPane(lessonList), BorderLayout.WEST);

        // Content
        lessonContent = new JTextArea();
        lessonContent.setEditable(false);
        add(new JScrollPane(lessonContent), BorderLayout.CENTER);

        // Button
        completeBtn = new JButton("Mark Completed");
        add(completeBtn, BorderLayout.SOUTH);

        // Events
        lessonList.addListSelectionListener(e -> onLessonSelected());
        completeBtn.addActionListener((ActionEvent ae) -> onMarkCompleted());

        setVisible(true);
    }

    private void onLessonSelected() {
        int index = lessonList.getSelectedIndex();
        if (index == -1) {
            return;
        }

        Lesson l = lessons.get(index);
        lessonContent.setText(l.getContent());
    }

   private void onMarkCompleted() {
    int index = lessonList.getSelectedIndex();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Select a lesson first!");
        return;
    }

    String lessonId = lessons.get(index).getLessonId();

    manager.markLessonCompleted(userId, courseId, lessonId);

    JOptionPane.showMessageDialog(this, "Lesson marked as completed!");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayLessons("12", "6").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
